# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# OARepo ecosystem is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
# This file was automatically generated by the integration tests to show which changes
# were applied to the package.
"""Changes performed by oarepo-integration-tools."""

# the code below is json, so need to define a couple of aliases just to be sure
true = True
"""JSON True."""

false = False
"""JSON False."""

features_incorporated = '[{"name":"configurable-service-resource","base":"v19.5.4"},{"name":"kwargs","base":"v19.5.4"},{"name":"pids-component-permission-check-args","base":"v19.5.4"}]'

oarepo_major_version = "13"

package_oarepo_version = "oarepo-19.5.4"

configuration = '{"name": "invenio-rdm-records", "oarepo": 13, "features": [{"name": "configurable-service-resource", "base": "v19.5.4"}, {"name": "kwargs", "base": "v19.5.4"}, {"name": "pids-component-permission-check-args", "base": "v19.5.4"}], "depends": [{"on": "invenio-records-resources"}, {"on": "invenio-drafts-resources"}], "entrypoints": [{"remove": "*", "keep": [{"group": "invenio_jsonschemas.schemas", "name": "invenio_rdm_records"}, {"group": "invenio_assets.webpack", "name": "invenio_rdm_records"}, {"group": "invenio_i18n.translations", "name": "invenio_rdm_records"}]}], "dependencies": [{"extra": "tests", "remove": "*"}], "package": "invenio-rdm-records", "invenio_version": "19.5.4", "version": "19.5.4"}'
