# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# OARepo ecosystem is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
# This file was automatically generated by the integration tests to show which changes
# were applied to the package.
"""Changes performed by oarepo-integration-tools."""

# the code below is json, so need to define a couple of aliases just to be sure
true = True
"""JSON True."""

false = False
"""JSON False."""

features_incorporated = (
    '[{"name":"transfers","base":"v10.9.1"},{"name":"optional-pids","base":"v10.9.2"}]'
)

oarepo_major_version = "12"

package_oarepo_version = "oarepo-10.9.3"

configuration = '{"name": "invenio-rdm-records", "oarepo": 12, "features": [{"name": "transfers", "base": "v10.9.1"}, {"name": "optional-pids", "base": "v10.9.2"}], "depends": [{"on": "invenio-records-resources"}, {"on": "invenio-drafts-resources"}], "entrypoints": [{"remove": "*", "keep": [{"group": "invenio_jsonschemas.schemas", "name": "invenio_rdm_records"}, {"group": "invenio_assets.webpack", "name": "invenio_rdm_records"}, {"group": "invenio_i18n.translations", "name": "invenio_rdm_records"}]}], "dependencies": [{"extra": "tests", "remove": "*"}], "frozen": [], "package": "invenio-rdm-records", "invenio_version": "10.9.3", "version": "10.9.3"}'
